export const DEFAULT_CONSTANT = "DEFAULT_CONSTANT";
export const COMENZAR_DESCARGA_PRODUCTOS = "COMENZAR_DESCARGA_PRODUCTOS";
export const DESCARGA_PRODUCTOS_EXITOSA = "DESCARGA_PRODUCTOS_EXITOSA";
export const DESCARGA_PRODUCTOS_ERROR = "DESCARGA_PRODUCTOS_ERROR";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
