export const EDITAR_PRODUCTO_EXITOSO = "EDITAR_PRODUCTO_EXITOSO";
export const EDITAR_PRODUCTO_ERROR = "EDITAR_PRODUCTO_ERROR";
export const OBTENER_PRODUCTO_EXITOSO = "OBTENER_PRODUCTO_EXITOSO";
export const OBTENER_PRODUCTO_ERROR = "OBTENER_PRODUCTO_ERROR";
export const EDITAR_PRODUCTO_COMENZAR = "EDITAR_PRODUCTO_COMENZAR";
